### ISSUE TITLE
[1.12.2] Weird behavior with Quick Leaf Decay

### ISSUE THREAD

**Issue by Lykrast** [arlyon/felling#11]
Breaking logs of a tree "normally" causes the leaves in the tree to quickly decay (as intended by Quick Leaf Decay and probably all similar mods).

But breaking a tree using a Felling axe does not seem to trigger that fast decay, the leaves decay much slower than usual. Breaking some block adjacent to one of them causes it to quickly decay and start some chain reaction that makes all the leaves go away in the expected speed though.

Probably related to block update behavior when breaking the logs.

**Comment by arlyon** [comment]
Thanks for the detailed description. My laptop is under repair but I'll see if I can have a look at it next week

**Comment by arlyon** [comment]
Looks like you'll need to set Player Decay to true. Currently felling breaks the blocks serverside so if you have that setting set to true (ie, the quick leaf decay only happens when caused by a player) then it won't trigger. I'm not sure how to get around it easily without triggering another BreakEvent.

Current recommendation is to set the "Player Decay" setting to false.
